port: 3000

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  name: ${DATABASE_NAME}
  pass: ${DATABASE_PASS}
  ssl: ${DATABASE_SSL}

jwt:
  access:
    secret: ${ACCESS_SECRET}
    expiresIn: ${ACCESS_EXPIRES_IN}
  refresh:
    secret: ${REFRESH_SECRET}
    expiresIn: ${REFRESH_EXPIRES_IN}
    
